Suggest and extension to the abstract and concrete syntaxes
w3c/rdf-star-wg pull request #22
Opened 2023-02-15 21:26 UTC by gkellogg

… for directly representing `text direction` as a component of a `literal`.

2023-02-15 22:32 UTC, domel reviewed
What about `rdf:CompoundLiteral`? Is it still on the table?

2023-02-15 23:24 UTC, gkellogg commented
> What about `rdf:CompoundLiteral`? Is it still on the table?

It’s still in the [document](https://github.com/w3c/rdf-star-wg/blob/main/docs/text-direction.md#the-rdfcompoundliteral-class), but I feel that both that and i18n are more historical notes at this time. I’m hoping the WG can decide on a direction so we can get on with it.

2023-02-16 00:12 UTC, TallTed requested changes
Just a few tweaks

2023-02-16 00:12 UTC, TallTed commented on docs/text-direction.md
> +> * ***if and only if the [datatype IRI](https://w3c.github.io/rdf-concepts/spec/#dfn-datatype-iri) is `http://www.w3.org/1999/02/22-rdf-syntax-ns#langString`, `text direction`, MUST BE empty or one
```suggestion
> * ***if and only if the [datatype IRI](https://w3c.github.io/rdf-concepts/spec/#dfn-datatype-iri) is `http://www.w3.org/1999/02/22-rdf-syntax-ns#langString`, `text direction`, MUST BE empty or one of `ltr` or `rtl`***.
```

2023-02-16 00:12 UTC, TallTed commented on docs/text-direction.md
> +> 1. If the literal is a [language-tagged string](https://w3c.github.io/rdf-concepts/spec/#dfn-language-tagged-string), then the literal value is a tuple consisting of its [lexical form](https://w3c.
```suggestion
> 1. If the literal is a [language-tagged string](https://w3c.github.io/rdf-concepts/spec/#dfn-language-tagged-string), then the literal value is a tuple consisting of its [lexical form](https://w3c.github.io/rdf-concepts/spec/#dfn-lexical-form), its [language tag](https://w3c.github.io/rdf-concepts/spec/#dfn-language-tag), and its `text direction`, in that order.
```

2023-02-16 00:12 UTC, TallTed commented on docs/text-direction.md
> +Concrete syntaxes, such as SPARQL and Turtle would change the definition of an `RDFLiteral`
```suggestion
Concrete syntaxes such as SPARQL and Turtle would change the definition of an `RDFLiteral`
```

2023-02-16 09:20 UTC, domel approved these changes

2023-03-23 17:13 UTC, merged